#使用显式契约
swagger: 2.0
info:
  version: 1.0.0
  title: swagger definition for io.provider.HelloRestService
  x-java-interface: io.provider.HelloRestService
basePath: /hello
produces:
 - application/json
paths:
  /sayhi:
    get:
      operationId: sayHi
      parameters:
      - name: name
        in: query
        required: false
        type: string
      responses:
        200:
          description: 正常返回
          schema:
            type: string
        default:
          description: 默认返回
          schema:
            type: string